# Header
menu:
  Home: /
  My Works: /works
  About: /about
  #Tags: /tags

rss: /atom.xml

# User Info
user_name:        #自己的名字
user_avatar:      #右侧作者栏的头像
user_location: China
user_description: ""
user_contact:     #签名
user_introduction: ""
github_username: 
twitter_username: 
weibo_username: 
zhihu_username: 
facebook_username: 
linkedin_username: 

# Content
excerpt_link: Read More
fancybox: true
#canvas-nest 点线粒子效果
nest: true                                             #false 可以关闭点线粒子效果
nest_line_color: "3,232,253 "            #线的颜色使用rgb，如红色（255，0，0）
nest_point_color: "3,232,253"          #点的颜色使用rgb，如红色（255，0，0），建议与线颜色一致
nest_opacity: 0.8                                    #透明度，1为不透明
nest_count: 100                                         #密度

# display widgets at the bottom of index pages (pagination == 2)
#index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
#archive_type: 'monthly'
#show_count: false

# 评论系统
# 不要用别人的 uid, 自己去注册一个吧
use_livere: true
livere_uid: 

use_disqus: false
disqus_url: 

# Miscellaneous
favicon: /favicon.png
#twitter:
#google_plus:
#fb_admins:
#fb_app_id:

# Highlight code
# do ensure u have closed all the highlight choices in ur root _config.yml
# currently we provided 6 choices based on highlight script
# highlight_default, highlight_light, highlight_github, highlight_rainbow, highlight_vs, highlight_atom
block_highlight: highlight_rainbow